import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ToasterContext from "@/components/ToasterContext";
import Navbar from "@/components/Navbar";
import UserFetcher from "@/components/UserFetcher";

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "EpidemIT | Where IT expertise spreads like wildfire, for everyone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" href="/logo-gambar.png" />
      <body className={roboto.className}>
        <ToasterContext />
        {/* <UserFetcher>{({ user }) => <Navbar user={user} />}</UserFetcher> */}
        {children}
      </body>
    </html>
  );
}
